import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import smileNoBg from "../../public/images/profile/smileNoBg.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";
import HireMe from "@/components/HireMe";
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Owoade Yusuf Adetunji</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 lg:w-full flex lg:flex-col items-center justify-center">
              <Image
                src={smileNoBg}
                alt="Adetunji"
                className="w-[500px] h-auto lg:hidden md:inline-block md:w-auto md:h-[350px] "
                priority
                sizes="(max-width: 768px) 100vw, (max-width:1200px) 50vw, 50vw"
              
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full  lg:text-center md:mt-8">
            
              <AnimatedText text='Turning Vision Into Reality With Code And Design.' className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl" />
              <p className="my-4 text-base font-medium md:text-sm ms:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center  ">
                <Link href='/YUSUFOWOADE.pdf' target={'_blank'}
                className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-solid border-transparent hover:border-dark border-2 
                
                dark:text-dark dark:bg-light hover:dark:text-light hover:dark:bg-dark hover:dark:border-light
                md:p-2  md:px-4 md:text-base

                "


                download={true}>Resume 
                <LinkArrow className={'w-6 ml-1'} /></Link>
                <Link href='mailto:yusufowoade2@gmail.com'
                className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base">Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="Adetunji" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
